services:
  environment:
    build:
      context: Dockerfiles/environment
      dockerfile: Dockerfile
    container_name: environment
    volumes:
      - .:/workspace:cached,rw
      - /var/run/docker.sock:/var/run/docker.sock:cached
    working_dir: /workspace
    tty: true
    stdin_open: true

  bun:
    image: oven/bun:1.3.6
    container_name: bun
    depends_on:
      - environment
    volumes:
      - .:/workspace:cached,rw
    working_dir: /workspace
    command: ["bun", "install"]
    tty: false
    stdin_open: false
